#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

COMPOSE="${COMPOSE:-docker compose}"

COMPUTE_ENV=(
  -e PYTHONPATH=/app/src
  -e PSYCOPG_CONNINFO="host=postgres port=5432 dbname=${POSTGRES_DB:-smoke} user=${POSTGRES_USER:-smoke} password=${POSTGRES_PASSWORD:-smoke}"
  -e DISPERSION_ENABLED="${DISPERSION_ENABLED:-0}"
  -e DISPERSION_MODEL_VERSION="${DISPERSION_MODEL_VERSION:-gaussian_v0}"
  -e DISPERSION_MAX_DISTANCE_KM="${DISPERSION_MAX_DISTANCE_KM:-150}"
  -e DISPERSION_CROSSWIND_SIGMA_KM="${DISPERSION_CROSSWIND_SIGMA_KM:-15}"
  -e DISPERSION_DOWNWIND_SIGMA_KM="${DISPERSION_DOWNWIND_SIGMA_KM:-75}"
  -e DISPERSION_MIN_WIND_SPEED_MPS="${DISPERSION_MIN_WIND_SPEED_MPS:-0.5}"
  -e DISPERSION_SOURCE_STRENGTH_MODE="${DISPERSION_SOURCE_STRENGTH_MODE:-frp}"
  -e DISPERSION_GRID_RESOLUTION_KM="${DISPERSION_GRID_RESOLUTION_KM:-10}"
  -e DISPERSION_MAX_TARGET_GEOGRAPHIES="${DISPERSION_MAX_TARGET_GEOGRAPHIES:-500}"
  -e DISPERSION_LOOKBACK_HOURS="${DISPERSION_LOOKBACK_HOURS:-24}"
  -e DISPERSION_USE_GRID_WEATHER="${DISPERSION_USE_GRID_WEATHER:-1}"
  -e DISPERSION_FALLBACK_TO_STATION_WIND="${DISPERSION_FALLBACK_TO_STATION_WIND:-1}"
  -e DISPERSION_WRITE_DEBUG_FIELDS="${DISPERSION_WRITE_DEBUG_FIELDS:-1}"
  -e DISPERSION_ALLOW_LARGE_RUN="${DISPERSION_ALLOW_LARGE_RUN:-0}"
  -e WIND_MATCH_RADIUS_KM="${WIND_MATCH_RADIUS_KM:-100}"
  -e WIND_MATCH_LOOKBACK_HOURS="${WIND_MATCH_LOOKBACK_HOURS:-6}"
  -e FIRE_WEATHER_MATCH_METHOD="${FIRE_WEATHER_MATCH_METHOD:-nearest_grid_cell}"
  -e SMOKE_RISK_GEOGRAPHIES="${SMOKE_RISK_GEOGRAPHIES:-both}"
)

echo "Python: compute dispersion exposures (DISPERSION_ENABLED=${DISPERSION_ENABLED:-0})..."
${COMPOSE} exec -T \
  "${COMPUTE_ENV[@]}" \
  spark-master python3 /app/src/wildfire_smoke/spark/compute_dispersion_exposure.py

echo "Dispersion computation complete."
