apiVersion: 1

datasources:
  - name: SmokePostgres
    uid: smoke_pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: smoke
    secureJsonData:
      password: smoke
    jsonData:
      database: smoke
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
